### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by simbaaa17** [simbaaa17/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by oleksiygarnik** [comment]
Oleksiy Garnik

Github: https://github.com/oleksiygarnik
Phone: +380971844085
Email: oleksiy.garnik27@gmail.com
Telegram: https://telegram.me/leha_garnich
